<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <WindowsControlFlowGuard>false</WindowsControlFlowGuard>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>c-letmeseepc</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Diagnostics.PerformanceCounter" Version="10.0.1" />
    <PackageReference Include="System.Management" Version="10.0.1" />
  </ItemGroup>
</Project>